fixup! (CR): build: apply moto defconfig fragment
fix the build error:
  [598 / 608] checking cached actions
   ERROR: /home/xizx/work/moto/8650/ctwov_rebase_r0023_1107/vendor_u/kernel_platform/msm-kernel/BUILD.bazel:346:21: Executing genrule //msm-kernel:pineapple_consolidate_dpm_image failed: (Exit 1): bash failed: error executing Genrule command (from target //msm-kernel:pineapple

   Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
   bazel-out/k8-fastbuild/bin/msm-kernel/pineapple_consolidate_build_config.generated: line 416: msm-kernel/build.config.moto: No such file or directory
   [600 / 608] Building dtbo @//msm-kernel:pineapple_consolidate_images_dtbo; 0s linux-sandbox

Change-Id: Idb6d954fd33cf9593a517efb8950ca06bd42d383
Reviewed-on: https://gerrit.mot.com/2788597
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Submit-Approved: Jira Key
Tested-by: Jira Key
Reviewed-by: Xu Zhang <zhangxu21@lenovo.com>
(cherry picked from commit 5339e9e791c20492fc741ef70dd3209dbc372704)
Reviewed-on: https://gerrit.mot.com/2806685
Reviewed-by: Qiong Xie <xieq2@motorola.com>
Reviewed-on: https://gerrit.mot.com/3016735
Reviewed-by: Zhenxin Xi <xizx@motorola.com>